name: Update Fork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - name: curl pull.git.ci
        shell: bash
        run: |
          curl -L -s https://pull.git.ci/process/sammcj/text-generation-webui -A "Mozilla/5.0 (compatible;  MSIE 7.01; Windows NT 5.0)"
